// +build go1.9

// Copyright 2017 Microsoft Corporation
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// This code was auto-generated by:
// github.com/Azure/azure-sdk-for-go/tools/profileBuilder
// commit ID: 0557aed5f03338a57db6ea921d282d5a85622abf

package cache

import original "github.com/Azure/azure-sdk-for-go/services/redis/mgmt/2015-08-01/cache"

const (
	DefaultBaseURI = original.DefaultBaseURI
)

type ManagementClient = original.ManagementClient
type RebootType = original.RebootType

const (
	AllNodes	RebootType	= original.AllNodes
	PrimaryNode	RebootType	= original.PrimaryNode
	SecondaryNode	RebootType	= original.SecondaryNode
)

type RedisKeyType = original.RedisKeyType

const (
	Primary		RedisKeyType	= original.Primary
	Secondary	RedisKeyType	= original.Secondary
)

type SkuFamily = original.SkuFamily

const (
	C	SkuFamily	= original.C
	P	SkuFamily	= original.P
)

type SkuName = original.SkuName

const (
	Basic		SkuName	= original.Basic
	Premium		SkuName	= original.Premium
	Standard	SkuName	= original.Standard
)

type RedisAccessKeys = original.RedisAccessKeys
type RedisCreateOrUpdateParameters = original.RedisCreateOrUpdateParameters
type RedisListKeysResult = original.RedisListKeysResult
type RedisListResult = original.RedisListResult
type RedisProperties = original.RedisProperties
type RedisReadableProperties = original.RedisReadableProperties
type RedisReadablePropertiesWithAccessKey = original.RedisReadablePropertiesWithAccessKey
type RedisRebootParameters = original.RedisRebootParameters
type RedisRegenerateKeyParameters = original.RedisRegenerateKeyParameters
type RedisResource = original.RedisResource
type RedisResourceWithAccessKey = original.RedisResourceWithAccessKey
type Resource = original.Resource
type Sku = original.Sku
type RedisClient = original.RedisClient

func NewRedisClient(subscriptionID string) RedisClient {
	return original.NewRedisClient(subscriptionID)
}
func NewRedisClientWithBaseURI(baseURI string, subscriptionID string) RedisClient {
	return original.NewRedisClientWithBaseURI(baseURI, subscriptionID)
}
func UserAgent() string {
	return original.UserAgent()
}
func Version() string {
	return original.Version()
}
func New(subscriptionID string) ManagementClient {
	return original.New(subscriptionID)
}
func NewWithBaseURI(baseURI string, subscriptionID string) ManagementClient {
	return original.NewWithBaseURI(baseURI, subscriptionID)
}
